SIGNING_VERSION="0.3"
ISSUER_HOST = "https://cp-private.data-container.net"
CREDENTIAL_PATH = "/oyd"
CREDENTIAL_TYPE = "OydCredential"
AUTH_REQUEST_URI="/agent/siop/definitions/sphereonWallet/auth-requests/"
